baseURL = "https://aquarian-age.github.io/"
languageCode = "zh-CN"
title = "浮生若梦"
tag = "tags"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true
## 字体
hasCJKLanguage = true
summaryLength = 140
## rss
disableKinds = ["RSS"]

disqusShortname = "Aquarian-Age"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "Amrta"

[params]
  author = "AmrtaShiva"
  subtitle = "浮若游生醉梦情，地天隔处戏游星，晨慕朝阳夕抱月，亦真亦幻游浮生......."
  keywords = ""
  description = "self"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "飞雪无情的博客"
  name = "飞雪无情的博客"
  url = "https://www.flysnow.org/"

[[params.links]]
  title = "The Internet Archive"
  name = "archive"
  url = "https://archive.is/"

[[params.links]]
  title = ""
  name = "世界数字图书馆"
  url = "https://www.wdl.org/zh/"

[[params.links]]
  title = "Stunning free images  royalty free stock"
  name = "Pixabay"
  url = "https://pixabay.com/"
  
[[params.links]]
  title = ""
  name = "500px"
  url = "https://500px.com/"
  
[[params.links]]
  title = ""
  name = "ping"
  url = "http://ping.pe/ping.php"
  
[[params.links]]
  title = "openSUSE"
  name = "我的OBS"
  url = "https://build.opensuse.org/project/show/home:liangzi"
  
[[params.links]]
  title = "What the World needs is Love"
  name = "OneWorld"
  url = "http://www.oneworldhealing.net/"
  
[[params.links]]
  title = ""
  name = "道卬"
  url = "https://www.daoon.com/ang/"
  
[[params.links]]
  title = "数字图书馆"
  name = "书格"
  url = "https://shuge.org/"

[[params.links]]
  title = ""
  name = "占星软件"
  url = "http://astrolog32v3.altervista.org/Documentation.zh.htm"

[[params.links]]
  title = ""
  name = "壽星萬年曆"
  url = "http://www.nongli.net/sxwnl/"
  
[[params.links]]
  title = ""
  name = "公历和农历日期对照"
  url = "https://ytliu0.github.io/ChineseCalendar/index_simp.html"

[[params.links]]
  title=""
  name ="吠陀經"
  url = "http://www.sacred-texts.com/hin/index.htm#vedas"

[[params.links]]
  title = ""
  name = "Solidot"
  url = "http://www.solidot.org"


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "Aquarian-Age.github.io"
  issueTerm = "title"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单
[menu]

  #[[menu.main]]
    #identifier = "tools"
    #name = "工具"
    #url = "/tools/"
    #weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
  
## 侧边栏广告位
# [[params.ads]]
 ### title = "【2019双12】ALL IN CLoud 低至1折"
 ## url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
 ## img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
# [[params.ads]]
 ## title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
 ## url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
 ## img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
# [[params.ads]]
 ## title = "【渠道专享低折扣】11月特惠 限时2折"
 ## url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
 ## img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
